# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tiny_mce_uploads}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-12-27}
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "app/controllers/attachments_controller.rb",
    "app/models/attachment.rb",
    "app/views/attachments/create.html.erb",
    "app/views/attachments/new.html.erb",
    "app/views/layouts/tiny_mce_uploads.html.erb",
    "config/routes.rb",
    "lib/generators/tiny_mce_uploads/templates/migration.rb",
    "lib/generators/tiny_mce_uploads/tiny_mce_uploads_generator.rb",
    "lib/tiny_mce_uploads.rb",
    "lib/tiny_mce_uploads/engine.rb",
    "lib/tiny_mce_uploads/exclude_tiny_mce_uploads_constraint.rb",
    "public/javascripts/tiny_mce/plugins/fupload/blank.htm",
    "public/javascripts/tiny_mce/plugins/fupload/css/template.css",
    "public/javascripts/tiny_mce/plugins/fupload/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/fupload/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/fupload/img/fupload.png",
    "public/javascripts/tiny_mce/plugins/fupload/js/template.js",
    "public/javascripts/tiny_mce/plugins/fupload/langs/en_dlg.js"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Allows for file uploads with TinyMCE}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tiny_mce>, ["~> 0.1.4"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<dynamic_form>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<tiny_mce>, ["~> 0.1.4"])
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_dependency(%q<dynamic_form>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<tiny_mce>, ["~> 0.1.4"])
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
    s.add_dependency(%q<dynamic_form>, ["~> 1.0.0"])
  end
end

